Task-2-1-1
ploddasha/Plodushcheva_OOP pull request #11
Opened 2023-02-21 04:44 UTC by ploddasha

2023-02-28 08:50 UTC, shadrina requested changes

2023-02-28 08:50 UTC, shadrina commented on Task-2-1-1/src/main/java/nsu/ru/plodushcheva/MultiThread.java
> +            }
Тут те же стримы можно использовать

2023-02-28 08:50 UTC, shadrina commented on Task-2-1-1/src/main/java/nsu/ru/plodushcheva/MultiThread.java
> +            }
Только обычные

2023-02-28 08:50 UTC, shadrina commented on Task-2-1-1/src/main/java/nsu/ru/plodushcheva/MultiThread.java
> +    public boolean func(int countOfThreads, List<Integer> arr) throws Exception {
Давай как-то логичнее назовем

2023-02-28 08:50 UTC, shadrina commented on Task-2-1-1/src/main/java/nsu/ru/plodushcheva/MultiThread.java
> +            throw new Exception("Wrong count of Threads");
`IllegalArgumentException`

2023-02-28 08:50 UTC, shadrina commented on Task-2-1-1/src/main/java/nsu/ru/plodushcheva/MultiThread.java
> +        int arrSize = arr.size() / countOfThreads;
Мне кажется, тут так просто не прокатит. Объяснила лично

2023-02-28 08:50 UTC, shadrina commented on Task-2-1-1/src/main/java/nsu/ru/plodushcheva/Successively.java
> +        return false;
Тут тоже можно обычный стрим

2023-02-28 08:50 UTC, shadrina commented on Task-2-1-1/src/main/java/nsu/ru/plodushcheva/MultiThread.java
> +    public boolean func(int countOfThreads, List<Integer> arr) throws Exception {
А она кстати не статик?

2023-03-07 08:01 UTC, ploddasha commented on Task-2-1-1/src/main/java/nsu/ru/plodushcheva/MultiThread.java
> +    public boolean func(int countOfThreads, List<Integer> arr) throws Exception {
Вроде нет 👀

2023-03-12 18:49 UTC, shadrina commented on Task-2-1-1/src/main/java/nsu/ru/plodushcheva/MultiThread.java
> +        int smallNumber = countOfThreads - largeNumber;
А какова идея этих вычислений?

2023-03-14 08:34 UTC, ploddasha commented on Task-2-1-1/src/main/java/nsu/ru/plodushcheva/MultiThread.java
> +        int smallNumber = countOfThreads - largeNumber;
Список делится на маленькие и большие подсписки. smallSize и largeSize - по сколько элементов в маленьких и больших подсписках. smallNumber и largeNumber - сколько таких подсписков соответственно.

2023-03-21 08:37 UTC, shadrina approved these changes

2023-05-07 09:31 UTC, merged