Task-2-2-1
ploddasha/Plodushcheva_OOP pull request #12
Opened 2023-04-17 21:19 UTC by ploddasha

2023-04-18 17:15 UTC, shadrina requested changes
Даша, прежде чем пытаться чинить основной баг с тем, что программа не завершается, почини вот эти мелкие недочеты. Возможно, проблема уйдет сама.

Ну а вообще если процесс не завершается, значит, за каким-то из тредов не уследила, и он не завершился. В крайнем случае можно вычислить виновника, используя какой-нибудь инструмент для мониторинга статуса тредов в java приложении. Можно нагуглить, можно у Леши спросить, он использовал.

2023-04-18 17:15 UTC, shadrina commented on Task-2-2-1/src/main/java/nsu/ru/plodushcheva/threads/Courier.java
> +    private static boolean working;
Модификатор static тут лишний, ты же каждого сотрудника отдельно останавливаешь.

2023-04-18 17:15 UTC, shadrina commented on Task-2-2-1/src/main/java/nsu/ru/plodushcheva/pizzeria/Stock.java
> +    public boolean addOrder2(Order order) throws InterruptedException {
Постарайся выбирать говорящие названия. В данном случае можно просто не добавлять постфикс "2" и сделать перегрузку метода `addOrder`

2023-04-18 17:15 UTC, shadrina commented on Task-2-2-1/src/main/java/nsu/ru/plodushcheva/threads/Courier.java
> +        Thread.currentThread().interrupt();
Вот это обсудили на паре

2023-04-18 17:15 UTC, shadrina commented on Task-2-2-1/src/main/java/nsu/ru/plodushcheva/threads/TakeOrders.java
> +    private static boolean working;
Опять же лишний static

2023-04-18 17:15 UTC, shadrina commented on Task-2-2-1/src/main/java/nsu/ru/plodushcheva/threads/TakeOrders.java
> +        working = true;
Вот эти два присваивания можно вынести выше, где поля декларируются. Можно, но необязательно.

2023-05-07 07:17 UTC, ploddasha commented
Теперь программа заканчивает свою работу! Оказалось, что проблема была не в потоках пиццерии, а в том, что я не закрывала поток таймера 😣

2023-05-10 14:00 UTC, shadrina approved these changes
Зато как приятно было найти фикс

2023-10-10 06:07 UTC, merged