Task-1-1-1
ploddasha/Plodushcheva_OOP pull request #4
Opened 2022-09-26 07:09 UTC by ploddasha

2022-09-28 05:09 UTC, shadrina requested changes
Не решены все варнинги во вкладке Files changed

2022-09-29 05:21 UTC, shadrina requested changes

2022-09-29 05:21 UTC, shadrina commented on Task-1-1-1/src/test/java/org/example/HeapSortTest.java
> +
Это reviewdog требует комментария тут? Лучше отсутствие комментария, чем лишний комментарий

2022-09-29 05:21 UTC, shadrina commented on Task-1-1-1/src/main/java/org/example/HeapSort.java
> +    public static void heapify(int[] arr, int n, int i) {
А ей точно стоит быть публичной? Используется вроде только внутри класса

2022-09-29 05:21 UTC, shadrina commented on Task-1-1-1/src/test/java/org/example/HeapSortTest.java
> +    private HeapSort heapSort = new HeapSort();
Нужен ли объект, если все вызываемые методы статические?

2022-09-29 19:18 UTC, ploddasha commented on Task-1-1-1/src/test/java/org/example/HeapSortTest.java
> +
reviewdog требует(

2022-10-03 10:32 UTC, shadrina requested changes

2022-10-03 10:32 UTC, shadrina commented on Task-1-1-1/src/main/java/org/example/HeapSort.java
> + */
Попробуй удалить эти комментарии в начале файлов. Не должен reviewdog их требовать

2022-10-03 10:32 UTC, shadrina commented on Task-1-1-1/src/main/java/org/example/HeapSort.java
> + */
Это слово уже написано в названии класса, давай напишем что-то осмысленное. Например, что этот класс делает.

2022-10-03 10:32 UTC, shadrina commented on Task-1-1-1/src/test/java/org/example/HeapSortTest.java
> +    private HeapSort heapSort;
Подойдешь на паре покажешь, как это вообще работает.

2022-10-03 10:32 UTC, shadrina commented on Task-1-1-1/src/test/java/org/example/HeapSortTest.java
> +    private HeapSort heapSort;
Каждый тест должен упасть с NPE

2022-10-03 10:32 UTC, shadrina commented on Task-1-1-1/script.bat
> +jar cf .\make\jar\HeapSort.jar -C .\make\bin .
Нет исполнения jar'а. Команда `java`

2022-10-05 08:34 UTC, shadrina approved these changes
Сдано

2022-12-25 06:40 UTC, merged